### ISSUE TITLE
Error when Gitlab Runner Download

### ISSUE THREAD

**Issue by MateusGabi** [wdhif/vagrant-gitlab-ci-runner#2]
![image](https://user-images.githubusercontent.com/14940643/38534735-c9fd5f06-3c4d-11e8-85d4-2353900bb185.png)

### Vagrantfile

```
  runner_version = "10.5.0"
  name = "Cent OS Box"
  runner_url = "----------"
  runner_tags = "Vagrant,CentOS"
  runner_token = "---------"
```

**Comment by wdhif** [comment]
The latest version of gitlab-runner doesn't use systemctl anymore to start the service, instead, it uses `gitlab-runner start`. I've created a branch to fix this issue. If you would be so kind to test it and tell me if it did fixed your issue. https://github.com/wdhif/vagrant-gitlab-ci-runner/pull/4

**Comment by MateusGabi** [comment]
Of course 😄 I'll test later.
